[project]
name = "githubcom-rs-mellea-workshop"
version = "0.1.0"
description = "Mellea workshop"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ipykernel>=7.0.1",
    "pip>=25.2",
]
